[2025-04-03T19:50:38.911+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-03T19:50:38.941+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_replay_etl.retry_failed_replays scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T19:50:38.956+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_replay_etl.retry_failed_replays scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T19:50:38.958+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-03T19:50:38.975+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): retry_failed_replays> on 2025-04-02 00:00:00+00:00
[2025-04-03T19:50:38.981+0000] {standard_task_runner.py:72} INFO - Started process 813 to run task
[2025-04-03T19:50:38.986+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pokemon_replay_etl', 'retry_failed_replays', 'scheduled__2025-04-02T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_replay_etl_dag.py', '--cfg-path', '/tmp/tmp28b4xqrm']
[2025-04-03T19:50:38.990+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask retry_failed_replays
[2025-04-03T19:50:39.046+0000] {task_command.py:467} INFO - Running <TaskInstance: pokemon_replay_etl.retry_failed_replays scheduled__2025-04-02T00:00:00+00:00 [running]> on host 93470d874d0b
[2025-04-03T19:50:39.122+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemon_replay_etl' AIRFLOW_CTX_TASK_ID='retry_failed_replays' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-02T00:00:00+00:00'
[2025-04-03T19:50:39.124+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-03T19:50:39.138+0000] {tasks.py:232} INFO - No failed replays to retry for format gen9vgc2024regh
[2025-04-03T19:50:39.140+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-03T19:50:39.149+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-03T19:50:39.150+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=pokemon_replay_etl, task_id=retry_failed_replays, run_id=scheduled__2025-04-02T00:00:00+00:00, execution_date=20250402T000000, start_date=20250403T195038, end_date=20250403T195039
[2025-04-03T19:50:39.202+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-03T19:50:39.221+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-03T19:50:39.224+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
